import { resizeImage } from '@starter-kit/utils/image';
import { addArticleJsonLd } from '@starter-kit/utils/seo/addArticleJsonLd';
import { getAutogeneratedPostOG } from '@starter-kit/utils/social/og';
// @ts-ignore
import handleMathJax from '@starter-kit/utils/handle-math-jax';
import { useEmbeds } from '@starter-kit/utils/renderer/hooks/useEmbeds';
import { loadIframeResizer } from '@starter-kit/utils/renderer/services/embed';
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { CoverImage } from './cover-image';
import { DateFormatter } from './date-formatter';
import { MarkdownToHtml } from './markdown-to-html';
import { PostFullFragment, PublicationFragment } from '../generated/graphql';
// @ts-ignore
import { triggerCustomWidgetEmbed } from '@starter-kit/utils/trigger-custom-widget-embed';

type PostContentProps = {
	post: PostFullFragment;
	publication: PublicationFragment;
};

type LocalPostContentProps = {
	post: {
		title: string;
		publishedAt?: string;
		content: { markdown: string };
		tags?: never;
		coverImage?: never;
		seo?: never;
		url?: never;
		subtitle?: never;
		brief?: never;
		ogMetaData?: never;
		readTimeInMinutes?: never;
		hasLatexInPost?: never;
		publication?: never;
	};
	publication: PublicationFragment;
	isLocal: true;
};

type Props = PostContentProps | LocalPostContentProps;

function isLocalPost(props: Props): props is LocalPostContentProps {
	return 'isLocal' in props && props.isLocal === true;
}

export const PostContent = (props: Props) => {
	const { post, publication } = props;
	const isLocal = isLocalPost(props);

	const highlightJsMonokaiTheme =
		'.hljs{display:block;overflow-x:auto;padding:.5em;background:#23241f}.hljs,.hljs-subst,.hljs-tag{color:#f8f8f2}.hljs-emphasis,.hljs-strong{color:#a8a8a2}.hljs-bullet,.hljs-link,.hljs-literal,.hljs-number,.hljs-quote,.hljs-regexp{color:#ae81ff}.hljs-code,.hljs-section,.hljs-selector-class,.hljs-title{color:#a6e22e}.hljs-strong{font-weight:700}.hljs-emphasis{font-style:italic}.hljs-attr,.hljs-keyword,.hljs-name,.hljs-selector-tag{color:#f92672}.hljs-attribute,.hljs-symbol{color:#66d9ef}.hljs-class .hljs-title,.hljs-params{color:#f8f8f2}.hljs-addition,.hljs-built_in,.hljs-builtin-name,.hljs-selector-attr,.hljs-selector-id,.hljs-selector-pseudo,.hljs-string,.hljs-template-variable,.hljs-type,.hljs-variable{color:#e6db74}.hljs-comment,.hljs-deletion,.hljs-meta{color:#75715e}';
	const [, setMobMount] = useState(false);
	const [canLoadEmbeds, setCanLoadEmbeds] = useState(false);
	useEmbeds({ enabled: canLoadEmbeds && !isLocal });

	const tagsList = !isLocal && post.tags
		? (post.tags ?? []).map((tag) => (
				<li key={tag.id}>
					<Link
						href={`/tag/${tag.slug}`}
						className="block rounded-full border px-2 py-1 font-medium hover:bg-slate-50 dark:border-neutral-800 dark:hover:bg-neutral-800 md:px-4"
					>
						#{tag.slug}
					</Link>
				</li>
		  ))
		: null;

	if (!isLocal && post.hasLatexInPost) {
		setTimeout(() => {
			handleMathJax(true);
		}, 500);
	}

	useEffect(() => {
		if (screen.width <= 425) {
			setMobMount(true);
		}

		if (!post || isLocal) {
			return;
		}

		// TODO:
		// More of an alert, did this below to wrap async funcs inside useEffect
		(async () => {
			await loadIframeResizer();
			triggerCustomWidgetEmbed(post.publication?.id.toString());
			setCanLoadEmbeds(true);
		})();
	}, []);

	const coverImageSrc =
		!isLocal && post.coverImage?.url
			? resizeImage(post.coverImage.url, {
					w: 1600,
					h: 840,
					c: 'thumb',
			  })
			: undefined;

	return (
		<>
			<Head>
				<title>{!isLocal && post.seo?.title ? post.seo.title : post.title}</title>
				{!isLocal && post.url && <link rel="canonical" href={post.url} />}
				<meta
					name="description"
					content={!isLocal && (post.seo?.description || post.subtitle || post.brief) || post.title}
				/>
				<meta property="twitter:card" content="summary_large_image" />
				<meta
					property="twitter:title"
					content={!isLocal && post.seo?.title ? post.seo.title : post.title}
				/>
				<meta
					property="twitter:description"
					content={!isLocal && (post.seo?.description || post.subtitle || post.brief) || post.title}
				/>
				{!isLocal && (
					<>
						<meta
							property="og:image"
							content={
								post.ogMetaData?.image ||
								post.coverImage?.url ||
								getAutogeneratedPostOG(post, publication)
							}
						/>
						<meta
							property="twitter:image"
							content={
								post.ogMetaData?.image ||
								post.coverImage?.url ||
								getAutogeneratedPostOG(post, publication)
							}
						/>
						<script
							type="application/ld+json"
							dangerouslySetInnerHTML={{
								__html: JSON.stringify(addArticleJsonLd(publication, post)),
							}}
						/>
					</>
				)}
				<style dangerouslySetInnerHTML={{ __html: highlightJsMonokaiTheme }}></style>
			</Head>
			<h1 className="text-4xl font-bold leading-tight tracking-tight text-black dark:text-white">
				{post.title}
			</h1>
			<div className="flex tracking-tight gap-2 text-neutral-600 dark:text-neutral-400">
				<DateFormatter dateString={post.publishedAt || new Date().toISOString()} />
				{!isLocal && post.readTimeInMinutes && (
					<>
						{'•'}
						<span>{post.readTimeInMinutes} min read</span>
					</>
				)}
			</div>
			{!!coverImageSrc && (
				<div className="w-full">
					<CoverImage title={post.title} priority={true} src={coverImageSrc} />
				</div>
			)}
			<MarkdownToHtml contentMarkdown={post.content.markdown} />
			{!isLocal && tagsList && (post.tags ?? []).length > 0 && (
				<div className="mx-auto w-full text-slate-600 dark:text-neutral-300 md:max-w-screen-md">
					<ul className="flex flex-row flex-wrap items-center gap-2">{tagsList}</ul>
				</div>
			)}
		</>
	);
};
